## 视频配置
video-config:
  ##Server地址前缀
  server-path: https:\\43.142.182.184:6001\
  ##视频保存路径
  video-save-path: videos
  ##视频封面保存路径
  video-cover-save-path: covers
  ##配置封面截取第几帧
  frame-num: 1
  ##feed流至多返回多少条视频
  feed-video-max-num: 15

##配置mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kdoushen?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: kO.yHw)(4WmD
    driver-class-name: com.mysql.cj.jdbc.Driver
  transaction:
    default-timeout: 3
  ##配置redis
  redis:
    host: localhost
    port: 6379

  activemq:
    broker-url: tcp://43.142.182.184:61616
    user: admin
    password: rzs.701
    pool:
      enabled: true
      max-connections: 10


server:
  port: 6001

#  ssl:
#      key-store: classpath:testhttps.keystore  #类路径下的自签证书
#      key-alias: testhttps # 证书别名
#      key-store-password: 123456 #证书密码
#      key-store-type: JKS # 证书类型
#      enabled: true  # 开启证书验证

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl




